# Use postgres/example user/password credentials
version: '3.1'

services:


  app:
    image: ocportal-nandi/admin/prod:${TAG-local}
    restart: 'no'
    extra_hosts:
      - "host.docker.internal:host-gateway" #required so docker connects to host interface (this is for sending emails)
    build:
      target: prod
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8090"
    volumes:
      - ./data/logs:/var/log/vifaa


  db:
    image: postgis/postgis:11-3.3
    restart: 'no'
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  mongo:
    image: mongo:4.2
    restart: 'no'
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
        - mongodata:/data/db
    ports:
      - "127.0.0.1:27017:27017"

volumes:
    pgdata:
    mongodata:
