version: '3.8'

services:

  app:
    image: ocportal-nandi/admin/prod:${TAG-local}
    restart: 'no'
    extra_hosts:
      - "host.docker.internal:host-gateway" #required so docker connects to host interface (this is for sending emails)
    build:
        target: prod
    depends_on:
      - db
      - mongo
    ports:
      - "8090:8090"
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgis/postgis:11-3.3
    restart: 'no'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env

  mongo:
    image: mongo:4.2
    restart: 'no'
    command: [--auth]
    volumes:
        - mongodata:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    env_file:
      - .env

volumes:
    pgdata:
    mongodata:
