name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v1
        with:
          registry: harbor.dgstg.org
          username: ${{ secrets.HARBOR_USERNAME  }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - uses: actions/checkout@v3
      - name: BuildAndPushDockerImages
        run: |
          docker build ./ --target prod -t harbor.dgstg.org/ocnandi/ocnandi-app:develop
          docker push harbor.dgstg.org/ocnandi/ocnandi-app:develop
          docker build ./nginx -t harbor.dgstg.org/ocnandi/ocnandi-web:develop
          docker push harbor.dgstg.org/ocnandi/ocnandi-web:develop
